language: r

env:
  global:
      - secure: A_LONG_ENCRYPTED_STRING

r_github_packages:
  - rstudio/bookdown

install: true
  - Rscript -e "if (!require('ggplot2')) install.packages('ggplot2')"

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh