language: r

env:
  global:
      - secure: A_LONG_ENCRYPTED_STRING

r_github_packages:
  - rstudio/bookdown

install:
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "if (!require('bookdown')) devtools::install_github('rstudio/bookdown')"
  - Rscript -e "if (!require('ggplot2')) install.packages('ggplot2')"

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh